name: Deploy to surge

on:
  push:
    branches:
      - staging # Set a branch to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_BARIKOI_API_KEY: ${{ secrets.NEXT_PUBLIC_BARIKOI_API_KEY }}
      NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL }}

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.13.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Build the project
      - name: Build
        run: npm run build

      # install surge
      - name: Install Surge
        run: npm install --global surge
        
      # Deploy to surge
      - name: Deploy
        run: surge  ./out cnl-dashboard-next-v2.surge.sh --token ${{ secrets.SURGE_TOKEN }}